#ifndef NF_TRAVERSAL_SHARED_H
#define NF_TRAVERSAL_SHARED_H

#define NF_TRAVERSAL_WALL 2
#define NF_TRAVERSAL_CABLE 3
#define NF_TRAVERSAL_DISABLED 7

#define NF_TRAVERSAL_WALL_MOUNT 1
#define NF_TRAVERSAL_WALL_ACTIVE 2
#define NF_TRAVERSAL_CABLE_MOUNT 3
#define NF_TRAVERSAL_CABLE_FORWARD 4
#define NF_TRAVERSAL_CABLE_REVERSE 5
#define NF_TRAVERSAL_CABLE_TURN_FORWARD 6
#define NF_TRAVERSAL_CABLE_TURN_REVERSE 7

#define NF_TRAVERSAL_PHASE(state) ((state) & 15)
#define NF_TRAVERSAL_ENTITY(state) ((state) >> 4)
#define NF_TRAVERSAL_STATE(entity, phase) (((entity) << 4) | (phase))

#define NF_TRAVERSAL_WALL_SPEED 40.8f
#define NF_TRAVERSAL_CABLE_SPEED 23.3f
#define NF_TRAVERSAL_WALL_MOUNT_MS 789.0f
#define NF_TRAVERSAL_CABLE_MOUNT_MS 1538.0f
#define NF_TRAVERSAL_TURN_MS 2200.0f
#define NF_TRAVERSAL_WALL_COOLDOWN_MS 2200.0f
#define NF_TRAVERSAL_CABLE_COOLDOWN_MS 1000.0f

#endif
